// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package io.gamioo.robot.entity;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientRequest_LoginArgsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 UserID = 1;
    /**
     * <code>optional int64 UserID = 1;</code>
     */
    boolean hasUserID();
    /**
     * <code>optional int64 UserID = 1;</code>
     */
    long getUserID();

    // optional string Token = 2;
    /**
     * <code>optional string Token = 2;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string Token = 2;</code>
     */
    String getToken();
    /**
     * <code>optional string Token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code io.gamioo.robot.entity.ClientRequest_LoginArgs}
   */
  public static final class ClientRequest_LoginArgs extends
      com.google.protobuf.GeneratedMessage
      implements ClientRequest_LoginArgsOrBuilder {
    // Use ClientRequest_LoginArgs.newBuilder() to construct.
    private ClientRequest_LoginArgs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientRequest_LoginArgs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientRequest_LoginArgs defaultInstance;
    public static ClientRequest_LoginArgs getDefaultInstance() {
      return defaultInstance;
    }

    public ClientRequest_LoginArgs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRequest_LoginArgs.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ClientRequest_LoginArgs> PARSER =
        new com.google.protobuf.AbstractParser<ClientRequest_LoginArgs>() {
      public ClientRequest_LoginArgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @Override
    public com.google.protobuf.Parser<ClientRequest_LoginArgs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 UserID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userID_;
    /**
     * <code>optional int64 UserID = 1;</code>
     */
    public boolean hasUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 UserID = 1;</code>
     */
    public long getUserID() {
      return userID_;
    }

    // optional string Token = 2;
    public static final int TOKEN_FIELD_NUMBER = 2;
    private Object token_;
    /**
     * <code>optional string Token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Token = 2;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userID_ = 0L;
      token_ = "";
    }
    public static ClientRequest_LoginArgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequest_LoginArgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequest_LoginArgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientRequest_LoginArgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientRequest_LoginArgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequest_LoginArgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientRequest_LoginArgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientRequest_LoginArgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientRequest_LoginArgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientRequest_LoginArgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientRequest_LoginArgs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.gamioo.robot.entity.ClientRequest_LoginArgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ClientRequest_LoginArgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientRequest_LoginArgs.class, Builder.class);
      }

      // Construct using io.gamioo.robot.entity.Message.ClientRequest_LoginArgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor;
      }

      public ClientRequest_LoginArgs getDefaultInstanceForType() {
        return ClientRequest_LoginArgs.getDefaultInstance();
      }

      public ClientRequest_LoginArgs build() {
        ClientRequest_LoginArgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientRequest_LoginArgs buildPartial() {
        ClientRequest_LoginArgs result = new ClientRequest_LoginArgs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userID_ = userID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      // optional int64 UserID = 1;
      private long userID_ ;
      /**
       * <code>optional int64 UserID = 1;</code>
       */
      public boolean hasUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 UserID = 1;</code>
       */
      public long getUserID() {
        return userID_;
      }
      /**
       * <code>optional int64 UserID = 1;</code>
       */
      public Builder setUserID(long value) {
        bitField0_ |= 0x00000001;
        userID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 UserID = 1;</code>
       */
      public Builder clearUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userID_ = 0L;
        onChanged();
        return this;
      }

      // optional string Token = 2;
      private Object token_ = "";
      /**
       * <code>optional string Token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Token = 2;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Token = 2;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.gamioo.robot.entity.ClientRequest_LoginArgs)
    }

    static {
      defaultInstance = new ClientRequest_LoginArgs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.gamioo.robot.entity.ClientRequest_LoginArgs)
  }

  public interface ServerResponse_LoginArgsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 ResultType = 1;
    /**
     * <code>optional int32 ResultType = 1;</code>
     */
    boolean hasResultType();
    /**
     * <code>optional int32 ResultType = 1;</code>
     */
    int getResultType();

    // optional string Message = 2;
    /**
     * <code>optional string Message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string Message = 2;</code>
     */
    String getMessage();
    /**
     * <code>optional string Message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code io.gamioo.robot.entity.ServerResponse_LoginArgs}
   */
  public static final class ServerResponse_LoginArgs extends
      com.google.protobuf.GeneratedMessage
      implements ServerResponse_LoginArgsOrBuilder {
    // Use ServerResponse_LoginArgs.newBuilder() to construct.
    private ServerResponse_LoginArgs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerResponse_LoginArgs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerResponse_LoginArgs defaultInstance;
    public static ServerResponse_LoginArgs getDefaultInstance() {
      return defaultInstance;
    }

    public ServerResponse_LoginArgs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerResponse_LoginArgs.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ServerResponse_LoginArgs> PARSER =
        new com.google.protobuf.AbstractParser<ServerResponse_LoginArgs>() {
      public ServerResponse_LoginArgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @Override
    public com.google.protobuf.Parser<ServerResponse_LoginArgs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 ResultType = 1;
    public static final int RESULTTYPE_FIELD_NUMBER = 1;
    private int resultType_;
    /**
     * <code>optional int32 ResultType = 1;</code>
     */
    public boolean hasResultType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 ResultType = 1;</code>
     */
    public int getResultType() {
      return resultType_;
    }

    // optional string Message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private Object message_;
    /**
     * <code>optional string Message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultType_ = 0;
      message_ = "";
    }
    public static ServerResponse_LoginArgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerResponse_LoginArgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerResponse_LoginArgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerResponse_LoginArgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerResponse_LoginArgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerResponse_LoginArgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ServerResponse_LoginArgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ServerResponse_LoginArgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ServerResponse_LoginArgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ServerResponse_LoginArgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ServerResponse_LoginArgs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.gamioo.robot.entity.ServerResponse_LoginArgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ServerResponse_LoginArgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerResponse_LoginArgs.class, Builder.class);
      }

      // Construct using io.gamioo.robot.entity.Message.ServerResponse_LoginArgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor;
      }

      public ServerResponse_LoginArgs getDefaultInstanceForType() {
        return ServerResponse_LoginArgs.getDefaultInstance();
      }

      public ServerResponse_LoginArgs build() {
        ServerResponse_LoginArgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerResponse_LoginArgs buildPartial() {
        ServerResponse_LoginArgs result = new ServerResponse_LoginArgs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultType_ = resultType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      // optional int32 ResultType = 1;
      private int resultType_ ;
      /**
       * <code>optional int32 ResultType = 1;</code>
       */
      public boolean hasResultType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 ResultType = 1;</code>
       */
      public int getResultType() {
        return resultType_;
      }
      /**
       * <code>optional int32 ResultType = 1;</code>
       */
      public Builder setResultType(int value) {
        bitField0_ |= 0x00000001;
        resultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ResultType = 1;</code>
       */
      public Builder clearResultType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultType_ = 0;
        onChanged();
        return this;
      }

      // optional string Message = 2;
      private Object message_ = "";
      /**
       * <code>optional string Message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string Message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Message = 2;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.gamioo.robot.entity.ServerResponse_LoginArgs)
    }

    static {
      defaultInstance = new ServerResponse_LoginArgs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.gamioo.robot.entity.ServerResponse_LoginArgs)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\022\026io.gamioo.robot.entity\"" +
      "8\n\027ClientRequest_LoginArgs\022\016\n\006UserID\030\001 \001" +
      "(\003\022\r\n\005Token\030\002 \001(\t\"?\n\030ServerResponse_Logi" +
      "nArgs\022\022\n\nResultType\030\001 \001(\005\022\017\n\007Message\030\002 \001" +
      "(\tB\002H\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_gamioo_robot_entity_ClientRequest_LoginArgs_descriptor,
              new String[] { "UserID", "Token", });
          internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_gamioo_robot_entity_ServerResponse_LoginArgs_descriptor,
              new String[] { "ResultType", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
