# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: build

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Clean with Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build --scan
      - name: Coverage with Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  finish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{success()}}
    steps:
      - run: echo "Build successfully on branch ${{ github.actor }}"


